clone:
	rm -rf common_core
	git clone git@github.com:KhalfaouiDriss/common_core.git common_core
push:
	git add . && \
        git status && \
        git commit -m "get_next_line" && \
        git push

testlibft:
        git clone https://github.com/Tripouille/libftTester.git libft/libftTester
testgnl:
        git clone https://github.com/Tripouille/gnlTester.git get_next_line/gnlTester
testprintf:
        git clone https://github.com/Tripouille/printfTester.git ft_printf/printfTester