server {

	listen 443 ssl;
	listen [::]:443 ssl;

	server_name "habdella.42.fr";

	ssl_certificate		/etc/nginx/ssl/cert-out.crt;
	ssl_certificate_key	/etc/nginx/ssl/key-out.key;
	ssl_protocols TLSv1.2 TLSv1.3;

	root /var/www/html;
	index index.php index.html;

	location / {
		try_files $uri $uri/ /index.php?$args;
	}

	location ~ \.php$ {
		include fastcgi_params;
		fastcgi_pass wordpress:9000;
		### tells PHP-FPM exactly where the file is on the disk ###
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
	}

	### Request Size limit ###
	client_max_body_size 10M;

	### Block PHP execution in uploads ###
	location ~* /wp-content/uploads/.*\.php$ { deny all; }

	### URL PATHs Protection ###
	location ~* /(wp-config\.php|\.env|\.git|\.htaccess) { deny all; }
}
